# Generated by Django 4.0 on 2024-01-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='party_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
