# Generated by Django 4.0 on 2024-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_myuser_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='party_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
