# Generated by Django 4.0 on 2024-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='party_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
