# Generated by Django 4.0 on 2024-01-13 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zarik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=300)),
                ('adress', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('inn_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('soato', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('report_date', models.DateField()),
                ('typeletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='mainletter.typeletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
