# Generated by Django 4.0 on 2024-01-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
