# Generated by Django 4.0 on 2024-01-13 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='pdfletterinstruction/unsigned/')),
                ('inn_number', models.CharField(max_length=15)),
                ('state', models.BooleanField(choices=[(True, 'Topshirdi'), (False, 'Topshirmadi')], default=False)),
                ('soato', models.CharField(max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdffiletemplate', to='mainletter.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('inn_number', models.CharField(max_length=15)),
                ('litter_number', models.PositiveBigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('soato', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('letter_date', models.DateTimeField(default=datetime.date(2024, 1, 20))),
                ('state', models.BooleanField(choices=[(True, 'Topshirdi'), (False, 'Topshirmadi')], default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letterinstructuion', to='mainletter.template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
