# Generated by Django 4.0 on 2024-01-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LetterInstruction',
        ),
    ]
