# Generated by Django 4.0 on 2024-01-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_delete_letterinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiletemplate',
            name='signed_state',
            field=models.BooleanField(default=False),
        ),
    ]
