# Generated by Django 4.0 on 2024-01-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_myuser_party_name'),
        ('mainletter', '0002_alter_template_body_alter_template_title'),
        ('letterapp', '0003_pdffiletemplate_signed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiletemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdffiletemplate_user', to='accountapp.myuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdffiletemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdffiletemplate_template', to='mainletter.template'),
        ),
    ]
