# Generated by Django 4.0 on 2024-01-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='pdfletterinstruction/signed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
