# Generated by Django 4.0 on 2024-01-13 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSummons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('letter_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('report_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('litter_number', models.CharField(max_length=15, unique=True)),
                ('inn_number', models.CharField(max_length=15)),
                ('stir_number', models.PositiveBigIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('report_date', models.DateTimeField()),
                ('created_date_add', models.DateTimeField(default=datetime.datetime(2024, 1, 18, 6, 46, 15, 255356, tzinfo=utc))),
                ('state', models.BooleanField(choices=[(True, 'Topshirdi'), (False, 'Topshirmadi')], default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountapp.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
